import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "../componets/providers";
import "./globals.css";
import TTAppLayout from "@/componets/TTAppLayout";
import { SessionProvider } from "@/componets/SessionProvider";
import TTLayoutWrapper from "@/componets/TTLayoutWrapper";
import QueryProvider from "@/componets/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            suppressHydrationWarning={true}
      >
         <QueryProvider>  
        <SessionProvider>
        <Providers>
     
        {children}
    
         </Providers>
         </SessionProvider>
         </QueryProvider>
      </body>
    </html>
  );
}
